version: '3'
services:
  eureka:
    image: localhost:5000/aman/eureka-server:otrs-SNAPSHOT
    ports:
      - "8761:8761"

  config:
    image: localhost:5000/aman/config-server:otrs-SNAPSHOT
    ports:
      - "8888:8888"

  restaurant-service:
    image: localhost:5000/aman/restaurant-service:otrs-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - eureka
      - config

  booking-service:
    image: localhost:5000/aman/booking-service:otrs-SNAPSHOT
    ports:
      - "8081:8080"
    links:
      - eureka
      - config

  user-service:
    image: localhost:5000/aman/user-service:otrs-SNAPSHOT
    restart: on-failure
    ports:
      - "8082:8080"
    links:
      - eureka
      - config

  zuul-server:
    image: localhost:5000/aman/zuul-server:otrs-SNAPSHOT
    ports:
      - "8765:8765"
